### ISSUE TITLE
Prepare the book website

### ISSUE THREAD

**Issue by aaruni96** [oscar-system/book.oscar-system.org#4]
Issue serves as a to-do tracker for https://github.com/oscar-system/Oscar.jl/issues/3707 .

## ToDo
- [x] replace the oscar logo with something else

## ToDo "eventually"
- [ ] once the book is out and has an URL/DOI etc., we should of course add that too

## Done
- [x] replace the sidebar color, replace "The OSCAR project" in the navbar with the book title #5 
- [x] create a top index page which has an enumerated list of all chapters, listing their titles and authors. The titles are hyperlinks to subpages (e.g chapter_05.md so you don't have to think about fancy file name). #7 
- [x] in each subpage add a title and again the author names, and dump in the code #7
- [x] then the book chapter authors can have their way and improve their pages. But they don't have to worry about what to put where etc., we already provide a framework
- [x] bonus points for setting up some javascript or so to add a little "copy to clipboard" link to each code block. #17

**Comment by fingolfin** [comment]
I think it is OK to close this now; I'd just open a new issue reminding us to add the DOI once it is available. I think the logo / layout is fine as it is right now
